name: Build templates
on:
  push:
  schedule:
    # Run weekly on Monday a 6am
    - cron: "0 6 15 * *"

jobs:
  build-template-base:
    name: Build template base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            scripts:
              - 'scripts/**'
              - 'files/**'
      - name: Build template
        if: steps.filter.outputs.scripts == 'true'
        run: pnpm install && pnpm run build:templates
      - name: Create Pull Request
        if: steps.filter.outputs.scripts == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          title: Updated templates
          body: |
            Update report
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          assignees: gpichot
          reviewers: gpichot
